#!/bin/sh

echo "preprocessing the math"
planck preprocess-math.cljs
echo "Building"
lein run
echo "Deploying blog post"
git add .
git commit -am "WIP"
git push
cd resources/public &&  git add . && git commit -am "WIP" && git push && cd ../../
